spring.application.name=srevices2

# 8080 被本机 nacos 容器占用，8081 是 srevices1
server.port=8082

spring.cloud.nacos.server-addr=localhost:8848
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
