spring.application.name=srevices1

# 8080 被本机 nacos 容器占用
server.port=8081

spring.cloud.nacos.server-addr=localhost:8848
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos

spring.config.import=optional:nacos:${spring.application.name}.properties
